Adding verify_tls parameter to disable ssl/tls verification
chaostoolkit-incubator/chaostoolkit-prometheus pull request #16
Opened 2022-02-08 09:31 UTC by rurod

Hello,

Adding the verify_tls parameter to give the possibility to query prometheus without checking it's certificate.

2023-09-18 11:39 UTC, mattiascockburn commented
This is super useful for testing and for circumstances where the use of a custom TLS store is not an option.

2023-09-18 14:52 UTC, rurod commented
Resolved conflicts so this can be merge. Still waiting on review.

2023-09-19 06:29 UTC, mattiascockburn commented
@Lawouach would you mind looking at this? It does not change defaults and makes using the probe itself a bit more flexible.

2023-09-19 06:42 UTC, Lawouach requested changes
Looks fine to me.

Can you had a changelog entry please?

2023-09-19 06:42 UTC, Lawouach commented on chaosprometheus/probes.py
> +    verify_tls: bool = True,
Could you put this before the `configuration` parameter? I tend, by convention, to keep the configuration and secrets as the last two arguments.

2023-09-19 12:30 UTC, rurod commented
Hi @Lawouach, done, hope its ok now.

2023-09-19 12:35 UTC, Lawouach approved these changes
LGTM

2023-09-19 12:35 UTC, Lawouach commented
Thank you @rurod and getting back to it after so long.

2023-09-19 12:38 UTC, Lawouach commented
I'll fix the linting after the merge. Thanks again!

2023-09-19 12:38 UTC, merged